Al.component['HelloAlumna'] = (function () { "use strict";
/* generated by Svelte v3.55.1 */
const {
	SvelteComponent,
	append_styles,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} = Al.shared;

function add_css(target) {
	append_styles(target, "svelte-ql8zzr", "@import 'https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200&display=swap';.container.svelte-ql8zzr{height:50vw;display:flex;align-items:center;justify-content:center;font:200 5rem 'Source Sans Pro', sans-serif;color:#b8af9e}");
}

function create_fragment(ctx) {
	let div;

	return {
		c() {
			div = element("div");
			div.textContent = `Welcome to ${name}!`;
			attr(div, "class", "container svelte-ql8zzr");
		},
		m(target, anchor) {
			insert(target, div, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
		}
	};
}

let name = 'Alumna v3';

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {}, add_css);
	}
}

return Component;
})();